### ISSUE TITLE
Fancontrol in VivoBook_ASUSLaptop X412FA

### ISSUE THREAD

**Issue by asfiya-inamdar** [leonmaxx/asus_fanmode#10]
Hi leonmaxx i was trying a command to change the value of thermal throttle policy by executing this command below
la -la /sys/devices/platform/asus-nb-wmi/

and the output is shown in the screenshot below..
![Screenshot from 2021-04-29 13-31-24](https://user-images.githubusercontent.com/83392644/116519540-37b21580-a8ef-11eb-8e29-c9e4cfc7231d.png)

What is the next echo command to change the thermal_throttle_policy so that i can run my fan at max speed?
Appreciate your help, thanks.

**Comment by leonmaxx** [comment]
Hi, as you can see in a screenshot there is no supported fan boost ACPI devices listed, and `asus_fanmode` will not work for you. On supported devices there should be `thermal_throttle_policy` or `fan_boost_mode` entry.  
  
But still, check `hwmon` subdirectory, there could be `fan*_*` entries that could allow you to control fan speeds.

**Comment by asfiya-inamdar** [comment]
Ok i see that, anyways thanks for the help.
