### ISSUE TITLE
Daemon fails at startup

### ISSUE THREAD

**Issue by ghost** [leonmaxx/asus_fanmode#11]
Laptop model ASUS TUF A15 2020(FX506IH)

`× asus_fanmode.service - ASUS Fan Mode Service
     Loaded: loaded (/usr/lib/systemd/system/asus_fanmode.service; enabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Tue 2021-07-13 01:23:30 IST; 32s ago
    Process: 479 ExecStart=/usr/bin/asus_fanmode (code=exited, status=19)
   Main PID: 479 (code=exited, status=19)
        CPU: 5ms

Jul 13 01:23:30 szz-asus systemd[1]: Started ASUS Fan Mode Service.
Jul 13 01:23:30 szz-asus asus_fanmode[479]: Cannot find Fan Mode sysfs entry!
Jul 13 01:23:30 szz-asus asus_fanmode[479]: Found CPU hwmon: /sys/class/hwmon/hwmon4/temp1_input
Jul 13 01:23:30 szz-asus systemd[1]: asus_fanmode.service: Main process exited, code=exited, status=19/n/a
Jul 13 01:23:30 szz-asus systemd[1]: asus_fanmode.service: Failed with result 'exit-code'.
`

**Comment by leonmaxx** [comment]
```
Jul 13 01:23:30 szz-asus asus_fanmode[479]: Cannot find Fan Mode sysfs entry!
```
Check if `asus-nb-wmi` is loaded and initialized.
