### ISSUE TITLE
How to change to boost mode on ASUS FX504GM?

### ISSUE THREAD

**Issue by steppewop** [leonmaxx/asus_fanmode#13]
First and foremost thank you so much for making this, I thought I was stuck with silent mode and was going to have to go back to WIndows.

But the problem is that I have no idea how to configure this utility and/or set a mode, it automatically sets for me but its not enough to not make my laptop thermal throttle, and even turn off in extreme circumstances.

This is how it's running:

`● asus_fanmode.service - ASUS Fan Mode Service
     Loaded: loaded (/usr/lib/systemd/system/asus_fanmode.service; enabled; vendor preset: disabled)
     Active: active (running) since Wed 2021-09-01 16:51:48 -03; 30min ago
   Main PID: 5278 (asus_fanmode)
      Tasks: 1 (limit: 9347)
     Memory: 284.0K
        CPU: 461ms
     CGroup: /system.slice/asus_fanmode.service
             └─5278 /usr/bin/asus_fanmode

set 01 17:15:02 laptop-daniel asus_fanmode[5278]: Switching fan mode to 'Silent', temperature: 47
set 01 17:19:06 laptop-daniel asus_fanmode[5278]: Switching fan mode to 'Normal', temperature: 72
set 01 17:19:50 laptop-daniel asus_fanmode[5278]: Switching fan mode to 'Normal', temperature: 71
set 01 17:19:55 laptop-daniel asus_fanmode[5278]: Switching fan mode to 'Silent', temperature: 49
set 01 17:20:40 laptop-daniel asus_fanmode[5278]: Switching fan mode to 'Normal', temperature: 70
set 01 17:20:54 laptop-daniel asus_fanmode[5278]: Switching fan mode to 'Silent', temperature: 53
set 01 17:20:58 laptop-daniel asus_fanmode[5278]: Switching fan mode to 'Normal', temperature: 73
set 01 17:21:28 laptop-daniel asus_fanmode[5278]: Switching fan mode to 'Silent', temperature: 54
set 01 17:21:32 laptop-daniel asus_fanmode[5278]: Switching fan mode to 'Normal', temperature: 74
set 01 17:22:02 laptop-daniel asus_fanmode[5278]: Switching fan mode to 'Silent', temperature: 54
`

The instructions on how to configure things were a bit vague for me since I'm new to Linux. How do I keep Boost mode always on or, alternatively, how do I set modes manually like in WIndows?

Thanks in advance. 

Update: I think I finally managed to configure it correctly, but the issues persists. I configured so boost mode is always on, but it doesn't work, the fans don't ramp up quick enough for my computer to not shut down under stress and it's pretty much always on SIlent mode for some reason. 

Here's the configuration file:

cpu_temp = /sys/class/hwmon/hwmon6/temp1_input

cpu_temp_divider = 1000

fan_mode = /sys/devices/platform/asus-nb-wmi/fan_boost_mode

# Modes
mode_silent    = 2
mode_normal    = 0
mode_overboost = 1

# Poll interval in milliseconds
poll = 500

# High - temperature at which mode is enabled
# Low  - temperature at which mode switches back
normal_high = 28
normal_low  = 20

overboost_high = 35
overboost_low  = 31

**Comment by leonmaxx** [comment]
First: are you sure that `hwmon6/temp1_input` is a CPU temperature sensor?  
Second: very bad sign that it shuts down, problem may be elsewhere.  
  
With config file that you posted, daemon should switch **FBM** to **overboost mode** once temperature on specified sensor reach 35° C (and I think it will never go back to normal/silent mode).  
  
To manually control FBM -  disable asus_fanmode, and use:
 1. `Fn+F5` hotkey.
 2. command: `echo 1 | sudo tee /sys/devices/platform/asus-nb-wmi/fan_boost_mode`

**Comment by steppewop** [comment]
> First: are you sure that `hwmon6/temp1_input` is a CPU temperature sensor?
> Second: very bad sign that it shuts down, problem may be elsewhere.
> 
> With config file that you posted, daemon should switch **FBM** to **overboost mode** once temperature on specified sensor reach 35° C (and I think it will never go back to normal/silent mode).
> 
> To manually control FBM - disable asus_fanmode, and use:
> 
>     1. `Fn+F5` hotkey.
> 
>     2. command: `echo 1 | sudo tee /sys/devices/platform/asus-nb-wmi/fan_boost_mode`

It's where "coretemp" is written on the "name" text file, so I believe so. 

This laptop is repasted and I'm using a cooling pad, so it never got over 60c in WIndows. What's happening is that the fans don't spin quick enough and the laptop ends up shutting itself down to avoid damage. This is very disappointing since in the Manjaro wiki it said this laptop is pretty much compatible out of the box.

That's what I want honestly, I don't mind the noise since I'm always wearing headphones. On Windows I always kept it at boost mode.

Unfortunately neither Fn + F5 or that command works. 

I would appreciate any help you can give me in figuring this out, thank you for the reply.

**Comment by leonmaxx** [comment]
> Unfortunately neither Fn + F5 or that command works.

Did you disabled `asus_fanmode` before trying?
Use: `sudo systemctl stop asus_fanmode`
