### ISSUE TITLE
asus_fanmode: unrecognized service

### ISSUE THREAD

**Issue by ph1losof** [leonmaxx/asus_fanmode#16]
Any support of systemd?

**Comment by leonmaxx** [comment]
https://github.com/leonmaxx/asus_fanmode#installation

**Comment by ph1losof** [comment]
'''
make
sudo make install
sudo systemctl enable asus_fanmode
sudo systemctl start asus_fanmode
'''
Installation guide, I don't have systemctl 
I only have systemd

**Comment by leonmaxx** [comment]
If you don't have `systemctl` then you don't have `systemd`.
