### ISSUE TITLE
compatibility with faustus

### ISSUE THREAD

**Issue by nxmbit** [leonmaxx/asus_fanmode#4]
Is it possible to use this daemon with faustus? ([https://github.com/hackbnw/faustus](url))
Faustus instead of `/sys/devices/platform/asus-nb-wmi/fan_boost_mode` and `/sys/devices/platform/asus-nb-wmi/throttle_thermal_policy` uses `/sys/devices/platform/faustus/fan_boost_mode` and `/sys/devices/platform/faustus/throttle_thermal_policy`. I am able to change fan speed using faustus but i would like to change it automatically using temperature thresholds using this daemon.

**Comment by leonmaxx** [comment]
Sure,
In `asus_fanmode.conf` uncomment `fan_mode` variable and set it to proper path.

Example:
```diff
-# fan_mode = /sys/devices/platform/asus-nb-wmi/throttle_thermal_policy
+fan_mode = /sys/devices/platform/faustus/fan_boost_mode
```

**Comment by nxmbit** [comment]
Working on FX505DT. Thanks!
