### ISSUE TITLE
Run Fans at max Speed

### ISSUE THREAD

**Issue by thermonucleardriven** [leonmaxx/asus_fanmode#9]
This code is great, but i am unable to understand ### what _values the modes(silent_mode, normal_mode,overboost_mode_) should have(Which now has 2,0,1 respectively) in order to run the fans at max speed irrespective of the temperature at all times.? Which in my case **(GT531GT)** i have seen a maximum of **6700 rpm**.

_I really don't care about the noise my fans make, it's actually pretty sweet at max rpm._

Also as i am a human by nature (suppressed by greed) wanted to **set the RPM of fans directly** in upcoming versions of this code.

_And Thanks a lot for this marvelous creation._

**Comment by leonmaxx** [comment]
Just disable/remove `asus_fanmode` and set fan mode manually:
```shell
echo 1 | sudo tee /sys/devices/platform/asus-nb-wmi/fan_boost_mode
```

**Comment by thermonucleardriven** [comment]
It says "tee: /sys/devices/platform/asus-nb-wmi/fan_boost_mode: Permission denied"  
here's the screenshot.
![Screenshot from 2021-04-18 14-33-27](https://user-images.githubusercontent.com/68279465/115140078-0dd93300-a053-11eb-8e3d-a92daa2b20f9.png)

**Comment by leonmaxx** [comment]
Try `echo 1 >/sys/devices/platform/asus-nb-wmi/fan_boost_mode`

> You don't need to use `sudo` if you're `root`.

**Comment by thermonucleardriven** [comment]
Permission denied again.
i don't have a file named "fan_mode_boost", and i even tried this command
"echo 1 >/sys/devices/platform/asus-nb-wmi/hwmon/hwmon6/pwm1_enable"
since hwmon6 had these files shown in below screenshot..

![Screenshot from 2021-04-18 15-06-59](https://user-images.githubusercontent.com/68279465/115140992-be493600-a057-11eb-9577-0bfd0a035c9d.png)

**Comment by leonmaxx** [comment]
Stop, show me output of this: `ls -la /sys/devices/platform/asus-nb-wmi/`

**Comment by thermonucleardriven** [comment]
Here you go..
![Screenshot from 2021-04-18 15-13-37](https://user-images.githubusercontent.com/68279465/115141210-b047e500-a058-11eb-9a5d-f1d6753ddc4a.png)

**Comment by leonmaxx** [comment]
Okay, proper command for your laptop: `echo 1 >/sys/devices/platform/asus-nb-wmi/throttle_thermal_policy`

**Comment by thermonucleardriven** [comment]
yeah it worked! so what can be the arguments for echo, i mean can it be echo 255 >/sys/devices.... (since 255 is max pwm value?)

**Comment by leonmaxx** [comment]
> i mean can it be echo 255

Nope! Proper values are:
```
0 - default mode
1 - overboost (max fan speed)
2 - silent (min fan speed)
```
Any other value is invalid.

**Comment by thermonucleardriven** [comment]
Thanks a lot man, your a saviour from the evil thermal throttling.
